#!/bin/bash

# ARCHIVE=../Roadshow.lha
ARCHIVE="$1"
OK=0

if [ -r "$ARCHIVE" ];
then
  OK=1
fi

if [ $OK -ne 1 ];
then
  echo "Splitter: Split large (LHA) files and create ADF files for Gotek drives"
  echo
  echo "Usage: $0 file.lha"
  echo
  exit 1;
fi

BASE=$(basename $ARCHIVE)
NAME=${BASE%.*}

ONEDISK=860000
FULLSIZE=$( stat -c %s  $ARCHIVE )
NUMDISKS=$(( ( $FULLSIZE + ( $ONEDISK - 1) )/ $ONEDISK ))

echo "Archive: $BASE"
echo "Name:${NAME}xx"
printf "Full Archive: %d\nPer disk: %d\nNumber of disks: %d\n" $FULLSIZE $ONEDISK $NUMDISKS

split --numeric-suffixes=1 -b $ONEDISK $ARCHIVE $NAME.

for i in $(seq 1 $NUMDISKS); do
  xdftool $NAME$i.adf create + format "$NAME$i" ffs
  xdftool $NAME$i.adf write $NAME.0$i
done

(
  printf "JOIN "
  for i in $(seq 1 $NUMDISKS); do
    printf "$NAME$i:$NAME.0$i "
  done
  printf "AS WORK:$BASE\n"
) > RunMe

xdftool ${NAME}1.adf write RunMe
xdftool ${NAME}1.adf protect RunMe SPARWED

for i in $(seq 1 $NUMDISKS); do
  xdftool $NAME$i.adf list
done
cat RunMe

rm ${NAME}.0?
rm RunMe
